# Generated by Django 3.2 on 2021-05-06 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210505_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lasttname',
            new_name='lastname',
        ),
    ]
