# Generated by Django 3.2 on 2021-05-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_oder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oder',
            new_name='Order',
        ),
    ]
